# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app
COPY requirements.txt
# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install  -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80



# Run app.py when the container launches
CMD ["uvicorn","app:app","--host","0.0.0.0"]
